export type SourceStage =
  | "model-ready"
  | "materialized"
  | "indexed"
  | "audited"
  | "blocked";

export type SourceRecord = {
  id: string;
  name: string;
  kind: string;
  entities: number;
  sequences: number;
  frames: number;
  occurrences: number;
  rights: number;
  stage: SourceStage;
  note: string;
};

export type GalleryRecord = {
  id: string;
  identity: string;
  entity: string;
  action: string;
  direction: string;
  run: string;
  target?: string;
  endpoint: string;
  euler?: string;
  label: string;
  caveat: string;
};

export const indexSnapshot = {
  exportedAt: "2026-08-13",
  bundleSha256:
    "64b8f0210583cbd5d994114a0490afa55d7821e115e12df19fdeceaee6e2a8e6",
  databaseSha256:
    "6f3802aaed83cdc1ee4e3a8a3588328433f11b8c5b708c2aa1bb7c6a6a1dca87",
  counts: {
    sources: 48,
    indexedSources: 12,
    entities: 5111,
    sequences: 26196,
    frames: 165403,
    occurrences: 318009,
    archiveMembers: 237749,
    blobs: 126712,
    mediaObservations: 123702,
    rightsObservations: 18,
  },
};

export const sources: SourceRecord[] = [
  {
    id: "mugen_mffa",
    name: "MUGEN / MFFA anime fighters",
    kind: "SFF sprites + AIR action timelines",
    entities: 227,
    sequences: 5906,
    frames: 47248,
    occurrences: 47248,
    rights: 0,
    stage: "materialized",
    note: "Offline research corpus, separate from the live SQLite snapshot. The current latent-motion manifest keeps 1,443 canonical identity/action clips; effect-only and subject-absent frames fail closed.",
  },
  {
    id: "flare_empyrean",
    name: "Flare: Empyrean Campaign",
    kind: "game animation definitions",
    entities: 1650,
    sequences: 15840,
    frames: 71064,
    occurrences: 202240,
    rights: 2,
    stage: "indexed",
    note: "Eight-direction fantasy entities; attachments remain separately modeled.",
  },
  {
    id: "openduelyst",
    name: "OpenDuelyst",
    kind: "TexturePacker atlases",
    entities: 2352,
    sequences: 5302,
    frames: 69020,
    occurrences: 77363,
    rights: 2,
    stage: "indexed",
    note: "Large atlas corpus with exact trim, rotation, alias, and role evidence.",
  },
  {
    id: "supertux",
    name: "SuperTux",
    kind: "creature manifests",
    entities: 96,
    sequences: 1010,
    frames: 7103,
    occurrences: 11735,
    rights: 2,
    stage: "blocked",
    note: "Indexed; model admission waits on exact flip and caller-controlled loop support.",
  },
  {
    id: "open_surge",
    name: "Open Surge",
    kind: "sprite declarations",
    entities: 353,
    sequences: 878,
    frames: 3484,
    occurrences: 4390,
    rights: 2,
    stage: "materialized",
    note: "Exact magenta color-key transform is now engine-evidenced and hash-bound.",
  },
  {
    id: "tmwa_client_data",
    name: "The Mana World",
    kind: "XML sprite definitions",
    entities: 107,
    sequences: 853,
    frames: 4153,
    occurrences: 5234,
    rights: 1,
    stage: "model-ready",
    note: "540 conservative model-ready multi-frame clips; current causal16 experiments use 16.",
  },
  {
    id: "wesnoth",
    name: "Battle for Wesnoth",
    kind: "WML frame sequences",
    entities: 248,
    sequences: 604,
    frames: 2526,
    occurrences: 6066,
    rights: 3,
    stage: "indexed",
    note: "Strict literal-animation subset; macros and conditional transforms stay quarantined.",
  },
  {
    id: "shattered_pixel_dungeon",
    name: "Shattered Pixel Dungeon",
    kind: "Java-defined sheets",
    entities: 103,
    sequences: 631,
    frames: 2439,
    occurrences: 4447,
    rights: 1,
    stage: "indexed",
    note: "Runtime inheritance and action timelines resolved from pinned source.",
  },
  {
    id: "freedoom",
    name: "Freedoom",
    kind: "Doom sprite families",
    entities: 19,
    sequences: 590,
    frames: 1633,
    occurrences: 1615,
    rights: 1,
    stage: "indexed",
    note: "Pose-heavy directional sprite families; timing remains deliberately unknown.",
  },
  {
    id: "space_station_14",
    name: "Space Station 14",
    kind: "RSI mob states",
    entities: 139,
    sequences: 246,
    frames: 297,
    occurrences: 2706,
    rights: 1,
    stage: "indexed",
    note: "Per-pack SPDX evidence; modular layers and noncanonical actions excluded.",
  },
  {
    id: "widelands",
    name: "Widelands",
    kind: "Lua workers & critters",
    entities: 22,
    sequences: 193,
    frames: 3272,
    occurrences: 2123,
    rights: 1,
    stage: "materialized",
    note: "Exact numbered-file timelines; action aliases are excluded from causal supervision.",
  },
  {
    id: "spritecook_free",
    name: "SpriteCook Free Assets",
    kind: "curated pixel sheets",
    entities: 22,
    sequences: 49,
    frames: 412,
    occurrences: 90,
    rights: 1,
    stage: "model-ready",
    note: "Small clean temporal corpus with 49 distinct sequences and seven action labels.",
  },
  {
    id: "universal_lpc",
    name: "Universal LPC",
    kind: "modular layer sheets",
    entities: 0,
    sequences: 0,
    frames: 0,
    occurrences: 0,
    rights: 1,
    stage: "audited",
    note: "87,962 layer sheets stream through a separate compositing manifest—not complete entities.",
  },
  {
    id: "tgstation",
    name: "/tg/station",
    kind: "DMI mob states",
    entities: 1150,
    sequences: 1680,
    frames: 60051,
    occurrences: 60051,
    rights: 0,
    stage: "audited",
    note: "Pinned pure audit: 401 DMIs and 1,680 whole-entity sequences; projection is not yet live.",
  },
];

export const actionCoverage = [
  ["idle", 3956],
  ["death", 3275],
  ["attack", 3144],
  ["hurt", 2820],
  ["run", 2212],
  ["cast", 1874],
  ["defend", 1874],
  ["shoot", 1801],
  ["walk", 1141],
  ["emote", 65],
] as const;

export const entityCoverage = [
  ["unknown", 3118],
  ["object", 1193],
  ["humanoid", 236],
  ["animal", 208],
  ["monster", 162],
  ["creature", 133],
  ["effect", 39],
  ["robot", 14],
] as const;

export const gallery: GalleryRecord[] = [
  {
    id: "skull-ice-walk-alpha4-6000",
    identity: "Ice skull",
    entity: "monster",
    action: "walk",
    direction: "down",
    run: "TMWA alpha-4 · 6,000 steps · palette64",
    target: "/gallery/skull-ice-walk-target.png",
    endpoint: "/gallery/skull-ice-walk-alpha4-6000.png",
    label: "Selected quality / steering checkpoint",
    caveat: "Exact in-sample replay; hard-alpha 144 and generated-only 64-color display decode.",
  },
  {
    id: "skull-ice-idle-alpha4-6000",
    identity: "Ice skull",
    entity: "monster",
    action: "idle",
    direction: "down",
    run: "TMWA alpha-4 · 6,000 steps · palette64",
    target: "/gallery/skull-ice-idle-target.png",
    endpoint: "/gallery/skull-ice-idle-alpha4-6000.png",
    label: "Same identity, alternate action",
    caveat: "Matched noise and non-action conditions isolate the idle/walk action token.",
  },
  {
    id: "logmonster-walk-alpha4-6000",
    identity: "Logmonster",
    entity: "monster",
    action: "walk",
    direction: "down",
    run: "TMWA alpha-4 · 6,000 steps · palette64",
    target: "/gallery/logmonster-walk-target.png",
    endpoint: "/gallery/logmonster-walk-alpha4-6000.png",
    label: "Large-silhouette quality sample",
    caveat: "In-sample reconstruction only; occasional isolated background pixels remain visible.",
  },
  {
    id: "sasquatch-walk",
    identity: "Sasquatch",
    entity: "monster",
    action: "walk",
    direction: "down",
    run: "TMWA causal16 · 2,000 steps",
    target: "/gallery/sasquatch-walk-target.png",
    endpoint: "/gallery/sasquatch-walk-endpoint.png",
    euler: "/gallery/sasquatch-walk-euler.png",
    label: "Matched target / generated walk",
    caveat: "Exact training identity and action; in-sample reconstruction, not novel generation.",
  },
  {
    id: "sasquatch-idle",
    identity: "Sasquatch",
    entity: "monster",
    action: "idle",
    direction: "down",
    run: "TMWA causal16 · 2,000 steps",
    target: "/gallery/sasquatch-idle-target.png",
    endpoint: "/gallery/sasquatch-idle-endpoint.png",
    label: "Matched target / generated idle",
    caveat: "Same identity, noise contract, canvas, phases, and decoder as the walk comparison.",
  },
  {
    id: "penguin-walk",
    identity: "Penguin",
    entity: "animal",
    action: "walk",
    direction: "down",
    run: "TMWA causal16 · 2,000 steps",
    target: "/gallery/penguin-walk-target.png",
    endpoint: "/gallery/penguin-walk-endpoint.png",
    euler: "/gallery/penguin-walk-euler.png",
    label: "Matched target / generated walk",
    caveat: "Endpoint sampling is numerically stronger, but visible output remains soft and speckled.",
  },
  {
    id: "logmonster-walk",
    identity: "Logmonster",
    entity: "monster",
    action: "walk",
    direction: "down",
    run: "TMWA causal16 · 2,000 steps",
    target: "/gallery/logmonster-walk-target.png",
    endpoint: "/gallery/logmonster-walk-endpoint.png",
    label: "Strongest causal pair",
    caveat: "This pair has the strongest target-distinct action response in the bounded batch.",
  },
  {
    id: "skull-ice-walk",
    identity: "Ice skull",
    entity: "monster",
    action: "walk",
    direction: "down",
    run: "TMWA causal16 · 2,000 steps",
    target: "/gallery/skull-ice-walk-target.png",
    endpoint: "/gallery/skull-ice-walk-endpoint.png",
    label: "High separation retention",
    caveat: "Generated idle/walk separation retains 88.5% of this target pair's distance.",
  },
  {
    id: "fetid-rat-idle",
    identity: "Fetid Rat",
    entity: "animal",
    action: "idle",
    direction: "unknown",
    run: "Fetid Rat · 1,500 steps · palette32",
    endpoint: "/gallery/fetid-rat-idle.png",
    label: "Decoded in-sample action",
    caveat: "Hard-alpha and 32-color display derivative; raw continuous RGBA remains canonical.",
  },
  {
    id: "fetid-rat-run",
    identity: "Fetid Rat",
    entity: "animal",
    action: "run",
    direction: "unknown",
    run: "Fetid Rat · 1,500 steps · palette32",
    endpoint: "/gallery/fetid-rat-run.png",
    label: "Decoded in-sample action",
    caveat: "One of four memorized actions sharing identity and matched-noise diagnostics.",
  },
  {
    id: "fetid-rat-attack",
    identity: "Fetid Rat",
    entity: "animal",
    action: "attack",
    direction: "unknown",
    run: "Fetid Rat · 1,500 steps · palette32",
    endpoint: "/gallery/fetid-rat-attack.png",
    label: "Decoded in-sample action",
    caveat: "Action-sensitive proof, not open-vocabulary semantics.",
  },
  {
    id: "fetid-rat-death",
    identity: "Fetid Rat",
    entity: "animal",
    action: "death",
    direction: "unknown",
    run: "Fetid Rat · 1,500 steps · palette32",
    endpoint: "/gallery/fetid-rat-death.png",
    label: "Decoded one-shot action",
    caveat: "Display derivative preserves eight authored output slots.",
  },
];

export const experimentSteps = [
  {
    step: 2000,
    pmMae: 0.041747,
    alphaIou: 0.863808,
    separation: 61.79,
    idleToWalk: 6,
    walkCorrect: 4,
    endpointLoss: 0.082645,
    report: "80dab913e390e8bed42241f383b8b327d8053575a76f746a07b34dc2ebca4fa0",
  },
  {
    step: 3000,
    pmMae: 0.030303,
    alphaIou: 0.92919,
    separation: 82.52,
    idleToWalk: 7,
    walkCorrect: 7,
    endpointLoss: 0.100295,
    report: "1c471220c2b47cdbd821d8921520db97722abe808f07f02a50f07a499fe035c5",
  },
  {
    step: 4000,
    pmMae: 0.025557,
    alphaIou: 0.949561,
    separation: 93.45,
    idleToWalk: 7,
    walkCorrect: 7,
    endpointLoss: 0.073079,
    report: "5365f324cf49ff1db0d421ce2145b0820d964a262f4b3f21f4874d35ea36e8ea",
  },
  {
    step: 5000,
    pmMae: 0.022242,
    alphaIou: 0.970442,
    separation: 101.34,
    idleToWalk: 8,
    walkCorrect: 7,
    endpointLoss: 0.05473,
    report: "3635c59396ff4f6e44f0e7623bdfa84e75213bdf56034e4a1a90c098897307d7",
  },
  {
    step: 6000,
    pmMae: 0.024113,
    alphaIou: 0.979635,
    separation: 110.21,
    idleToWalk: 8,
    walkCorrect: 8,
    endpointLoss: 0.041985,
    report: "7fef539de909b6612de95c40168c98de02f25f93078433adcd6ec529f26e01de",
  },
] as const;

export const causalGates = [
  { label: "Foreground error", observed: "0.06286", threshold: "< 0.06864 at 5k", pass: true },
  { label: "Alpha IoU @127", observed: "97.96%", threshold: "> 97.04% at 5k", pass: true },
  { label: "Action separation", observed: "110.21%", threshold: "> 101.34% at 5k", pass: true },
  { label: "Global PM-RGBA", observed: "0.02411", threshold: "5k was 0.02224", pass: false },
] as const;

export const pipelineStages = [
  {
    id: "discover",
    index: "01",
    title: "Discover",
    status: "operational",
    summary: "Registered adapters and metadata-only discovery collect stable source identities.",
    details: "48 registered source systems; YouTube is discovery metadata only, never a media downloader.",
  },
  {
    id: "acquire",
    index: "02",
    title: "Acquire + CAS",
    status: "operational",
    summary: "Guarded downloads become immutable SHA-256 objects before parsing.",
    details: "126,712 blobs; every write checks the 100 GiB free-space floor.",
  },
  {
    id: "inspect",
    index: "03",
    title: "Inspect",
    status: "operational",
    summary: "Archives, PNG/APNG/GIF media, sheets, palettes, and unsafe members are audited.",
    details: "237,749 archive members and 123,702 media observations in the latest bundle.",
  },
  {
    id: "project",
    index: "04",
    title: "Project",
    status: "operational",
    summary: "Source-specific runtime semantics become entities, actions, timelines, and evidence edges.",
    details: "26,196 indexed sequences; uncertain transforms and loop semantics fail closed.",
  },
  {
    id: "snapshot",
    index: "05",
    title: "Snapshot",
    status: "operational",
    summary: "Leakage-aware grouped splits preserve identity, pack, blob, and duplicate components.",
    details: "Temporal, pose-only, source-filtered, and model-ready policies are separately explicit.",
  },
  {
    id: "materialize",
    index: "06",
    title: "Materialize",
    status: "operational",
    summary: "Exact source rectangles become hash-verified RGBA tensors without interpolation.",
    details: "Native buckets, pixel transforms, phases, timing, and every pre/post hash remain linked.",
  },
  {
    id: "train",
    index: "07",
    title: "Latent motion DiT",
    status: "research",
    summary: "A canonical sprite reference plus action tokens drive spatiotemporal flow in a frozen sprite-autoencoder latent space.",
    details: "The broad MUGEN run uses 1,443 canonical clips across 225 identities. Direct-pixel PixelDiT remains a historical baseline; held-out action transfer is the deciding test.",
  },
  {
    id: "evaluate",
    index: "08",
    title: "Evaluate",
    status: "operational",
    summary: "Matched noise, target pairing, alpha, temporal, and causal action-swap metrics.",
    details: "Every preview points to canonical arrays; display decodes never replace raw evidence.",
  },
] as const;

export const evidenceHashes = [
  ["Provenance bundle", "64b8f0210583cbd5d994114a0490afa55d7821e115e12df19fdeceaee6e2a8e6"],
  ["Live index checkpoint", "6f3802aaed83cdc1ee4e3a8a3588328433f11b8c5b708c2aa1bb7c6a6a1dca87"],
  ["TMWA alpha-4 6k checkpoint", "394880c5e067059f01b1f9c2462e75bae66705944e11f04c0a5b058e9689b761"],
  ["TMWA alpha-4 6k matched eval", "a1e151788c00f977d5b167e1e39a71bb02682ac8234cbd235c6a496afb5504cd"],
  ["TMWA alpha-4 decode bundle", "25c78b85b6dc9f6c463e081c5504203881d134842c3bc7427e2d0c2612a22aa0"],
  ["TMWA alpha-4 5k matched eval", "3fd894d77e6bb24a20c14f5060f3f9e913eb935a9c616471202c252fe5716cf7"],
] as const;
